# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Add_participant.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_participant(object):
    def setupUi(self, Add_participant):
        Add_participant.setObjectName("Add_participant")
        Add_participant.resize(608, 376)
        self.gridLayout = QtWidgets.QGridLayout(Add_participant)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_phone_number_participant = QtWidgets.QLineEdit(Add_participant)
        self.lineEdit_phone_number_participant.setObjectName("lineEdit_phone_number_participant")
        self.gridLayout.addWidget(self.lineEdit_phone_number_participant, 2, 0, 1, 1)
        self.label_add_participant_event = QtWidgets.QLabel(Add_participant)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_add_participant_event.setFont(font)
        self.label_add_participant_event.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_participant_event.setObjectName("label_add_participant_event")
        self.gridLayout.addWidget(self.label_add_participant_event, 1, 0, 1, 4)
        self.tree_add_participant_to_event = QtWidgets.QTreeWidget(Add_participant)
        self.tree_add_participant_to_event.setObjectName("tree_add_participant_to_event")
        self.tree_add_participant_to_event.header().setDefaultSectionSize(147)
        self.tree_add_participant_to_event.header().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tree_add_participant_to_event, 4, 0, 1, 4)
        self.pushButton_find_participant = QtWidgets.QPushButton(Add_participant)
        self.pushButton_find_participant.setObjectName("pushButton_find_participant")
        self.gridLayout.addWidget(self.pushButton_find_participant, 2, 2, 1, 1)
        self.lineEdit_second_name_participant = QtWidgets.QLineEdit(Add_participant)
        self.lineEdit_second_name_participant.setObjectName("lineEdit_second_name_participant")
        self.gridLayout.addWidget(self.lineEdit_second_name_participant, 2, 1, 1, 1)
        self.label_username_login_role = QtWidgets.QLabel(Add_participant)
        self.label_username_login_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_login_role.setObjectName("label_username_login_role")
        self.gridLayout.addWidget(self.label_username_login_role, 0, 2, 1, 2)
        self.pushButton_add_selected_participant = QtWidgets.QPushButton(Add_participant)
        self.pushButton_add_selected_participant.setObjectName("pushButton_add_selected_participant")
        self.gridLayout.addWidget(self.pushButton_add_selected_participant, 5, 0, 1, 1)
        self.pushButton_ok = QtWidgets.QPushButton(Add_participant)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout.addWidget(self.pushButton_ok, 5, 3, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Add_participant)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 5, 2, 1, 1)

        self.retranslateUi(Add_participant)
        self.pushButton_add_selected_participant.clicked.connect(Add_participant.show) # type: ignore
        self.pushButton_ok.clicked.connect(Add_participant.show) # type: ignore
        self.pushButton_cancel.clicked.connect(Add_participant.close) # type: ignore
        self.pushButton_find_participant.clicked.connect(Add_participant.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Add_participant)
        Add_participant.setTabOrder(self.lineEdit_phone_number_participant, self.lineEdit_second_name_participant)
        Add_participant.setTabOrder(self.lineEdit_second_name_participant, self.pushButton_find_participant)
        Add_participant.setTabOrder(self.pushButton_find_participant, self.tree_add_participant_to_event)
        Add_participant.setTabOrder(self.tree_add_participant_to_event, self.pushButton_add_selected_participant)
        Add_participant.setTabOrder(self.pushButton_add_selected_participant, self.pushButton_ok)
        Add_participant.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, Add_participant):
        _translate = QtCore.QCoreApplication.translate
        Add_participant.setWindowTitle(_translate("Add_participant", "Event"))
        self.lineEdit_phone_number_participant.setPlaceholderText(_translate("Add_participant", "Номер телефона..."))
        self.label_add_participant_event.setText(_translate("Add_participant", "Добавить участника мероприятия"))
        self.tree_add_participant_to_event.headerItem().setText(0, _translate("Add_participant", "Телефон"))
        self.tree_add_participant_to_event.headerItem().setText(1, _translate("Add_participant", "Фамилия"))
        self.tree_add_participant_to_event.headerItem().setText(2, _translate("Add_participant", "Имя"))
        self.tree_add_participant_to_event.headerItem().setText(3, _translate("Add_participant", "Отчество"))
        self.pushButton_find_participant.setText(_translate("Add_participant", "Найти"))
        self.lineEdit_second_name_participant.setPlaceholderText(_translate("Add_participant", "Фамилия..."))
        self.label_username_login_role.setText(_translate("Add_participant", "username_login_role"))
        self.pushButton_add_selected_participant.setText(_translate("Add_participant", "Добавить выбранного"))
        self.pushButton_ok.setText(_translate("Add_participant", "ОК"))
        self.pushButton_cancel.setText(_translate("Add_participant", "Отмена"))
