# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Create_event.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Create_event(object):
    def setupUi(self, Create_event):
        Create_event.setObjectName("Create_event")
        Create_event.setWindowModality(QtCore.Qt.NonModal)
        Create_event.resize(500, 282)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Create_event.sizePolicy().hasHeightForWidth())
        Create_event.setSizePolicy(sizePolicy)
        Create_event.setMinimumSize(QtCore.QSize(500, 282))
        Create_event.setMaximumSize(QtCore.QSize(500, 282))
        self.gridLayout = QtWidgets.QGridLayout(Create_event)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_event_theme = QtWidgets.QLineEdit(Create_event)
        self.lineEdit_event_theme.setObjectName("lineEdit_event_theme")
        self.gridLayout.addWidget(self.lineEdit_event_theme, 4, 0, 1, 4)
        self.lineEdit_event_name = QtWidgets.QLineEdit(Create_event)
        self.lineEdit_event_name.setObjectName("lineEdit_event_name")
        self.gridLayout.addWidget(self.lineEdit_event_name, 3, 0, 1, 4)
        self.pushButton_select_organization = QtWidgets.QPushButton(Create_event)
        self.pushButton_select_organization.setObjectName("pushButton_select_organization")
        self.gridLayout.addWidget(self.pushButton_select_organization, 5, 0, 1, 1)
        self.lineEdit_event_country = QtWidgets.QLineEdit(Create_event)
        self.lineEdit_event_country.setObjectName("lineEdit_event_country")
        self.gridLayout.addWidget(self.lineEdit_event_country, 6, 3, 1, 1)
        self.event_DateTime_start = QtWidgets.QDateTimeEdit(Create_event)
        self.event_DateTime_start.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 6, 1), QtCore.QTime(9, 0, 0)))
        self.event_DateTime_start.setDate(QtCore.QDate(2023, 6, 1))
        self.event_DateTime_start.setObjectName("event_DateTime_start")
        self.gridLayout.addWidget(self.event_DateTime_start, 6, 0, 1, 1)
        self.lineEdit_selected_organization = QtWidgets.QLineEdit(Create_event)
        self.lineEdit_selected_organization.setReadOnly(True)
        self.lineEdit_selected_organization.setObjectName("lineEdit_selected_organization")
        self.gridLayout.addWidget(self.lineEdit_selected_organization, 5, 2, 1, 2)
        self.pushButton_cancel = QtWidgets.QPushButton(Create_event)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 11, 2, 1, 1)
        self.label_create_event = QtWidgets.QLabel(Create_event)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_create_event.setFont(font)
        self.label_create_event.setAlignment(QtCore.Qt.AlignCenter)
        self.label_create_event.setObjectName("label_create_event")
        self.gridLayout.addWidget(self.label_create_event, 1, 0, 1, 4)
        self.pushButton_ok = QtWidgets.QPushButton(Create_event)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout.addWidget(self.pushButton_ok, 11, 3, 1, 1)
        self.label_username_login_role = QtWidgets.QLabel(Create_event)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_username_login_role.setFont(font)
        self.label_username_login_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_login_role.setObjectName("label_username_login_role")
        self.gridLayout.addWidget(self.label_username_login_role, 0, 2, 1, 2)
        self.lineEdit_event_comment = QtWidgets.QLineEdit(Create_event)
        self.lineEdit_event_comment.setObjectName("lineEdit_event_comment")
        self.gridLayout.addWidget(self.lineEdit_event_comment, 10, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 2, 1, 1)
        self.event_DateTime_end = QtWidgets.QDateTimeEdit(Create_event)
        self.event_DateTime_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 6, 1), QtCore.QTime(14, 0, 0)))
        self.event_DateTime_end.setObjectName("event_DateTime_end")
        self.gridLayout.addWidget(self.event_DateTime_end, 7, 0, 1, 1)
        self.lineEdit_event_city = QtWidgets.QLineEdit(Create_event)
        self.lineEdit_event_city.setObjectName("lineEdit_event_city")
        self.gridLayout.addWidget(self.lineEdit_event_city, 7, 3, 1, 1)
        self.lineEdit_type_event = QtWidgets.QLineEdit(Create_event)
        self.lineEdit_type_event.setObjectName("lineEdit_type_event")
        self.gridLayout.addWidget(self.lineEdit_type_event, 7, 2, 1, 1)

        self.retranslateUi(Create_event)
        self.pushButton_ok.clicked.connect(Create_event.show)
        self.pushButton_cancel.clicked.connect(Create_event.close)
        self.pushButton_select_organization.clicked.connect(Create_event.show)
        QtCore.QMetaObject.connectSlotsByName(Create_event)
        Create_event.setTabOrder(self.lineEdit_event_name, self.lineEdit_event_theme)
        Create_event.setTabOrder(self.lineEdit_event_theme, self.pushButton_select_organization)
        Create_event.setTabOrder(self.pushButton_select_organization, self.event_DateTime_start)
        Create_event.setTabOrder(self.event_DateTime_start, self.event_DateTime_end)
        Create_event.setTabOrder(self.event_DateTime_end, self.lineEdit_type_event)
        Create_event.setTabOrder(self.lineEdit_type_event, self.lineEdit_event_country)
        Create_event.setTabOrder(self.lineEdit_event_country, self.lineEdit_event_city)
        Create_event.setTabOrder(self.lineEdit_event_city, self.lineEdit_event_comment)
        Create_event.setTabOrder(self.lineEdit_event_comment, self.pushButton_ok)
        Create_event.setTabOrder(self.pushButton_ok, self.pushButton_cancel)
        Create_event.setTabOrder(self.pushButton_cancel, self.lineEdit_selected_organization)

    def retranslateUi(self, Create_event):
        _translate = QtCore.QCoreApplication.translate
        Create_event.setWindowTitle(_translate("Create_event", "Fast Community"))
        self.lineEdit_event_theme.setPlaceholderText(_translate("Create_event", "Тема мероприятия..."))
        self.lineEdit_event_name.setPlaceholderText(_translate("Create_event", "Наименование мероприятия..."))
        self.pushButton_select_organization.setText(_translate("Create_event", "Выбрать организацию"))
        self.lineEdit_event_country.setPlaceholderText(_translate("Create_event", "Страна..."))
        self.lineEdit_selected_organization.setPlaceholderText(_translate("Create_event", "Организация..."))
        self.pushButton_cancel.setText(_translate("Create_event", "Отмена"))
        self.label_create_event.setText(_translate("Create_event", "Создание нового мероприятия"))
        self.pushButton_ok.setText(_translate("Create_event", "OK"))
        self.label_username_login_role.setText(_translate("Create_event", "username_login_role"))
        self.lineEdit_event_comment.setPlaceholderText(_translate("Create_event", "Комментарий..."))
        self.lineEdit_event_city.setPlaceholderText(_translate("Create_event", "Город..."))
        self.lineEdit_type_event.setText(_translate("Create_event", "НИР"))
        self.lineEdit_type_event.setPlaceholderText(_translate("Create_event", "Тип мероприятия..."))
