# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Choose_organization.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Choose_organization(object):
    def setupUi(self, Choose_organization):
        Choose_organization.setObjectName("Choose_organization")
        Choose_organization.setEnabled(True)
        Choose_organization.resize(600, 400)
        self.gridLayout = QtWidgets.QGridLayout(Choose_organization)
        self.gridLayout.setObjectName("gridLayout")
        self.label_username_login_role = QtWidgets.QLabel(Choose_organization)
        self.label_username_login_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_login_role.setObjectName("label_username_login_role")
        self.gridLayout.addWidget(self.label_username_login_role, 0, 1, 1, 1)
        self.tree_organizations_list = QtWidgets.QTreeWidget(Choose_organization)
        self.tree_organizations_list.setObjectName("tree_organizations_list")
        self.tree_organizations_list.headerItem().setText(0, "1")
        self.tree_organizations_list.header().setDefaultSectionSize(170)
        self.tree_organizations_list.header().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tree_organizations_list, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(Choose_organization)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(568, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Cancel = QtWidgets.QPushButton(Choose_organization)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.pushButton_OK = QtWidgets.QPushButton(Choose_organization)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout.addWidget(self.pushButton_OK)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)

        self.retranslateUi(Choose_organization)
        QtCore.QMetaObject.connectSlotsByName(Choose_organization)

    def retranslateUi(self, Choose_organization):
        _translate = QtCore.QCoreApplication.translate
        Choose_organization.setWindowTitle(_translate("Choose_organization", "Dialog"))
        self.label_username_login_role.setText(_translate("Choose_organization", "username_login_role"))
        self.label.setText(_translate("Choose_organization", "Список организаций"))
        self.pushButton_Cancel.setText(_translate("Choose_organization", "Отмена"))
        self.pushButton_OK.setText(_translate("Choose_organization", "Добавить"))
