# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Event.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Event(object):
    def setupUi(self, Event):
        Event.setObjectName("Event")
        Event.resize(1128, 571)
        self.gridLayout = QtWidgets.QGridLayout(Event)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_close_access = QtWidgets.QPushButton(Event)
        self.pushButton_close_access.setObjectName("pushButton_close_access")
        self.gridLayout.addWidget(self.pushButton_close_access, 8, 5, 1, 1)
        self.tree_event_participants_list = QtWidgets.QTreeWidget(Event)
        self.tree_event_participants_list.setHeaderHidden(False)
        self.tree_event_participants_list.setColumnCount(9)
        self.tree_event_participants_list.setObjectName("tree_event_participants_list")
        self.tree_event_participants_list.headerItem().setText(1, "№")
        self.tree_event_participants_list.headerItem().setText(2, "Фамилия")
        self.tree_event_participants_list.headerItem().setText(3, "Имя")
        self.tree_event_participants_list.headerItem().setText(4, "Отчество")
        self.tree_event_participants_list.headerItem().setText(5, "Город")
        self.tree_event_participants_list.headerItem().setText(6, "Телефон")
        self.tree_event_participants_list.header().setDefaultSectionSize(20)
        self.tree_event_participants_list.header().setHighlightSections(True)
        self.tree_event_participants_list.header().setMinimumSectionSize(20)
        self.tree_event_participants_list.header().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tree_event_participants_list, 17, 0, 8, 7)
        self.pushButton_cancel = QtWidgets.QPushButton(Event)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 26, 6, 1, 1)
        self.label_total_participants = QtWidgets.QLabel(Event)
        self.label_total_participants.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_participants.setObjectName("label_total_participants")
        self.gridLayout.addWidget(self.label_total_participants, 16, 5, 1, 1)
        self.lineEdit_event_theme = QtWidgets.QLineEdit(Event)
        self.lineEdit_event_theme.setObjectName("lineEdit_event_theme")
        self.gridLayout.addWidget(self.lineEdit_event_theme, 8, 0, 1, 4)
        self.label_username_login_role = QtWidgets.QLabel(Event)
        self.label_username_login_role.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.label_username_login_role.setFont(font)
        self.label_username_login_role.setAutoFillBackground(False)
        self.label_username_login_role.setTextFormat(QtCore.Qt.AutoText)
        self.label_username_login_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_login_role.setObjectName("label_username_login_role")
        self.gridLayout.addWidget(self.label_username_login_role, 2, 5, 1, 3)
        self.line = QtWidgets.QFrame(Event)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 15, 0, 1, 8)
        self.label_Event = QtWidgets.QLabel(Event)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_Event.setFont(font)
        self.label_Event.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Event.setObjectName("label_Event")
        self.gridLayout.addWidget(self.label_Event, 2, 2, 1, 2)
        self.pushButton_ok = QtWidgets.QPushButton(Event)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout.addWidget(self.pushButton_ok, 26, 7, 1, 1)
        self.comboBox_event_status = QtWidgets.QComboBox(Event)
        self.comboBox_event_status.setObjectName("comboBox_event_status")
        self.comboBox_event_status.addItem("")
        self.comboBox_event_status.addItem("")
        self.comboBox_event_status.addItem("")
        self.comboBox_event_status.addItem("")
        self.gridLayout.addWidget(self.comboBox_event_status, 2, 0, 1, 1)
        self.pushButton_one_email = QtWidgets.QPushButton(Event)
        self.pushButton_one_email.setObjectName("pushButton_one_email")
        self.gridLayout.addWidget(self.pushButton_one_email, 19, 7, 1, 1)
        self.pushButton_analisis_doc = QtWidgets.QPushButton(Event)
        self.pushButton_analisis_doc.setObjectName("pushButton_analisis_doc")
        self.gridLayout.addWidget(self.pushButton_analisis_doc, 12, 5, 1, 1)
        self.pushButton_email = QtWidgets.QPushButton(Event)
        self.pushButton_email.setObjectName("pushButton_email")
        self.gridLayout.addWidget(self.pushButton_email, 20, 7, 1, 1)
        self.lineEdit_event_name = QtWidgets.QLineEdit(Event)
        self.lineEdit_event_name.setObjectName("lineEdit_event_name")
        self.gridLayout.addWidget(self.lineEdit_event_name, 7, 0, 1, 4)
        self.pushButton_open_access = QtWidgets.QPushButton(Event)
        self.pushButton_open_access.setObjectName("pushButton_open_access")
        self.gridLayout.addWidget(self.pushButton_open_access, 7, 5, 1, 1)
        self.lineEdit_selected_organization = QtWidgets.QLineEdit(Event)
        self.lineEdit_selected_organization.setReadOnly(True)
        self.lineEdit_selected_organization.setObjectName("lineEdit_selected_organization")
        self.gridLayout.addWidget(self.lineEdit_selected_organization, 10, 1, 1, 1)
        self.pushButton_add_event_participant = QtWidgets.QPushButton(Event)
        self.pushButton_add_event_participant.setObjectName("pushButton_add_event_participant")
        self.gridLayout.addWidget(self.pushButton_add_event_participant, 25, 0, 1, 1)
        self.pushButton_download_xls = QtWidgets.QPushButton(Event)
        self.pushButton_download_xls.setObjectName("pushButton_download_xls")
        self.gridLayout.addWidget(self.pushButton_download_xls, 21, 7, 1, 1)
        self.event_DateTime_start = QtWidgets.QDateTimeEdit(Event)
        self.event_DateTime_start.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 6, 1), QtCore.QTime(10, 30, 0)))
        self.event_DateTime_start.setDate(QtCore.QDate(2023, 6, 1))
        self.event_DateTime_start.setObjectName("event_DateTime_start")
        self.gridLayout.addWidget(self.event_DateTime_start, 12, 0, 1, 1)
        self.pushButton_del_event_participant = QtWidgets.QPushButton(Event)
        self.pushButton_del_event_participant.setObjectName("pushButton_del_event_participant")
        self.gridLayout.addWidget(self.pushButton_del_event_participant, 26, 0, 1, 1)
        self.label_list_participants = QtWidgets.QLabel(Event)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_list_participants.setFont(font)
        self.label_list_participants.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_participants.setObjectName("label_list_participants")
        self.gridLayout.addWidget(self.label_list_participants, 16, 2, 1, 3)
        self.label_wait_load_xls = QtWidgets.QLabel(Event)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_wait_load_xls.setFont(font)
        self.label_wait_load_xls.setAutoFillBackground(True)
        self.label_wait_load_xls.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wait_load_xls.setObjectName("label_wait_load_xls")
        self.gridLayout.addWidget(self.label_wait_load_xls, 26, 1, 1, 5)
        self.lineEdit_event_comment = QtWidgets.QLineEdit(Event)
        self.lineEdit_event_comment.setObjectName("lineEdit_event_comment")
        self.gridLayout.addWidget(self.lineEdit_event_comment, 14, 0, 1, 6)
        self.pushButton_load_xls = QtWidgets.QPushButton(Event)
        self.pushButton_load_xls.setObjectName("pushButton_load_xls")
        self.gridLayout.addWidget(self.pushButton_load_xls, 25, 2, 1, 1)
        self.pushButton_select_organization = QtWidgets.QPushButton(Event)
        self.pushButton_select_organization.setObjectName("pushButton_select_organization")
        self.gridLayout.addWidget(self.pushButton_select_organization, 10, 0, 1, 1)
        self.event_DateTime_end = QtWidgets.QDateTimeEdit(Event)
        self.event_DateTime_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 6, 3), QtCore.QTime(15, 0, 0)))
        self.event_DateTime_end.setDate(QtCore.QDate(2000, 6, 3))
        self.event_DateTime_end.setObjectName("event_DateTime_end")
        self.gridLayout.addWidget(self.event_DateTime_end, 13, 0, 1, 1)
        self.lineEdit_type_event = QtWidgets.QLineEdit(Event)
        self.lineEdit_type_event.setObjectName("lineEdit_type_event")
        self.gridLayout.addWidget(self.lineEdit_type_event, 10, 2, 1, 1)
        self.lineEdit_event_country = QtWidgets.QLineEdit(Event)
        self.lineEdit_event_country.setText("")
        self.lineEdit_event_country.setObjectName("lineEdit_event_country")
        self.gridLayout.addWidget(self.lineEdit_event_country, 12, 1, 1, 1)
        self.lineEdit_event_city = QtWidgets.QLineEdit(Event)
        self.lineEdit_event_city.setObjectName("lineEdit_event_city")
        self.gridLayout.addWidget(self.lineEdit_event_city, 13, 1, 1, 1)

        self.retranslateUi(Event)
        self.pushButton_cancel.clicked.connect(Event.close)
        QtCore.QMetaObject.connectSlotsByName(Event)
        Event.setTabOrder(self.lineEdit_event_name, self.lineEdit_event_theme)
        Event.setTabOrder(self.lineEdit_event_theme, self.pushButton_select_organization)
        Event.setTabOrder(self.pushButton_select_organization, self.event_DateTime_start)
        Event.setTabOrder(self.event_DateTime_start, self.tree_event_participants_list)
        Event.setTabOrder(self.tree_event_participants_list, self.pushButton_add_event_participant)
        Event.setTabOrder(self.pushButton_add_event_participant, self.pushButton_del_event_participant)
        Event.setTabOrder(self.pushButton_del_event_participant, self.pushButton_open_access)
        Event.setTabOrder(self.pushButton_open_access, self.pushButton_close_access)
        Event.setTabOrder(self.pushButton_close_access, self.pushButton_analisis_doc)
        Event.setTabOrder(self.pushButton_analisis_doc, self.pushButton_email)
        Event.setTabOrder(self.pushButton_email, self.pushButton_ok)
        Event.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, Event):
        _translate = QtCore.QCoreApplication.translate
        Event.setWindowTitle(_translate("Event", "Fast Community"))
        self.pushButton_close_access.setText(_translate("Event", "Закрыть доступ для организации"))
        self.tree_event_participants_list.headerItem().setText(0, _translate("Event", "id"))
        self.tree_event_participants_list.headerItem().setText(7, _translate("Event", "e-mail"))
        self.tree_event_participants_list.headerItem().setText(8, _translate("Event", "Пароль"))
        self.pushButton_cancel.setText(_translate("Event", "Отмена"))
        self.label_total_participants.setText(_translate("Event", "Кол-во участников ___"))
        self.lineEdit_event_theme.setPlaceholderText(_translate("Event", "Тема мероприятия..."))
        self.label_username_login_role.setText(_translate("Event", "username_login_role"))
        self.label_Event.setText(_translate("Event", "Мероприятие  "))
        self.pushButton_ok.setText(_translate("Event", "OK"))
        self.comboBox_event_status.setItemText(0, _translate("Event", "Запланировано"))
        self.comboBox_event_status.setItemText(1, _translate("Event", "В работе"))
        self.comboBox_event_status.setItemText(2, _translate("Event", "Проведено"))
        self.comboBox_event_status.setItemText(3, _translate("Event", "Отменено"))
        self.pushButton_one_email.setText(_translate("Event", "email одному"))
        self.pushButton_analisis_doc.setText(_translate("Event", "Анализ загруженных документов"))
        self.pushButton_email.setText(_translate("Event", "e-mail всем"))
        self.lineEdit_event_name.setPlaceholderText(_translate("Event", "Наименование мероприятия..."))
        self.pushButton_open_access.setText(_translate("Event", "Открыть доступ для организации"))
        self.lineEdit_selected_organization.setPlaceholderText(_translate("Event", "Организация..."))
        self.pushButton_add_event_participant.setText(_translate("Event", "Добавить участника"))
        self.pushButton_download_xls.setText(_translate("Event", "выгрузить XLS"))
        self.pushButton_del_event_participant.setText(_translate("Event", "Удалить участника"))
        self.label_list_participants.setText(_translate("Event", "Список участников"))
        self.label_wait_load_xls.setText(_translate("Event", "Подождите, идет загрузка файла и создание профилей участников"))
        self.lineEdit_event_comment.setPlaceholderText(_translate("Event", "Комментарий к мероприятию..."))
        self.pushButton_load_xls.setWhatsThis(_translate("Event", "Активна только если участников = 0"))
        self.pushButton_load_xls.setText(_translate("Event", "Загрузить файл с участниками (*.xls)"))
        self.pushButton_select_organization.setText(_translate("Event", "Выбрать организацию"))
        self.lineEdit_type_event.setText(_translate("Event", "НИР"))
        self.lineEdit_type_event.setPlaceholderText(_translate("Event", "Тип мероприятия..."))
        self.lineEdit_event_country.setPlaceholderText(_translate("Event", "Страна..."))
        self.lineEdit_event_city.setPlaceholderText(_translate("Event", "Город..."))
