# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Event.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Event(object):
    def setupUi(self, Event):
        Event.setObjectName("Event")
        Event.resize(1029, 538)
        self.gridLayout = QtWidgets.QGridLayout(Event)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_selected_organization = QtWidgets.QLineEdit(Event)
        self.lineEdit_selected_organization.setReadOnly(True)
        self.lineEdit_selected_organization.setObjectName("lineEdit_selected_organization")
        self.gridLayout.addWidget(self.lineEdit_selected_organization, 7, 1, 1, 1)
        self.pushButton_analisis_doc = QtWidgets.QPushButton(Event)
        self.pushButton_analisis_doc.setObjectName("pushButton_analisis_doc")
        self.gridLayout.addWidget(self.pushButton_analisis_doc, 9, 4, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Event)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 20, 5, 1, 1)
        self.label_total_participants = QtWidgets.QLabel(Event)
        self.label_total_participants.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_participants.setObjectName("label_total_participants")
        self.gridLayout.addWidget(self.label_total_participants, 11, 4, 1, 1)
        self.label_Event = QtWidgets.QLabel(Event)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_Event.setFont(font)
        self.label_Event.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Event.setObjectName("label_Event")
        self.gridLayout.addWidget(self.label_Event, 1, 1, 1, 3)
        self.pushButton_email = QtWidgets.QPushButton(Event)
        self.pushButton_email.setObjectName("pushButton_email")
        self.gridLayout.addWidget(self.pushButton_email, 14, 6, 1, 1)
        self.lineEdit_event_city = QtWidgets.QLineEdit(Event)
        self.lineEdit_event_city.setObjectName("lineEdit_event_city")
        self.gridLayout.addWidget(self.lineEdit_event_city, 9, 2, 1, 1)
        self.pushButton_add_event_participant = QtWidgets.QPushButton(Event)
        self.pushButton_add_event_participant.setObjectName("pushButton_add_event_participant")
        self.gridLayout.addWidget(self.pushButton_add_event_participant, 19, 0, 1, 1)
        self.pushButton_select_organization = QtWidgets.QPushButton(Event)
        self.pushButton_select_organization.setObjectName("pushButton_select_organization")
        self.gridLayout.addWidget(self.pushButton_select_organization, 7, 0, 1, 1)
        self.pushButton_ok = QtWidgets.QPushButton(Event)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout.addWidget(self.pushButton_ok, 20, 6, 1, 1)
        self.lineEdit_event_name = QtWidgets.QLineEdit(Event)
        self.lineEdit_event_name.setObjectName("lineEdit_event_name")
        self.gridLayout.addWidget(self.lineEdit_event_name, 5, 0, 1, 3)
        self.lineEdit_type_event = QtWidgets.QLineEdit(Event)
        self.lineEdit_type_event.setObjectName("lineEdit_type_event")
        self.gridLayout.addWidget(self.lineEdit_type_event, 9, 1, 1, 1)
        self.event_dateTime = QtWidgets.QDateTimeEdit(Event)
        self.event_dateTime.setObjectName("event_dateTime")
        self.gridLayout.addWidget(self.event_dateTime, 9, 0, 1, 1)
        self.pushButton_print_list = QtWidgets.QPushButton(Event)
        self.pushButton_print_list.setObjectName("pushButton_print_list")
        self.gridLayout.addWidget(self.pushButton_print_list, 15, 6, 1, 1)
        self.lineEdit_event_theme = QtWidgets.QLineEdit(Event)
        self.lineEdit_event_theme.setObjectName("lineEdit_event_theme")
        self.gridLayout.addWidget(self.lineEdit_event_theme, 6, 0, 1, 3)
        self.label_list_participants = QtWidgets.QLabel(Event)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_list_participants.setFont(font)
        self.label_list_participants.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_participants.setObjectName("label_list_participants")
        self.gridLayout.addWidget(self.label_list_participants, 11, 1, 1, 3)
        self.pushButton_del_event_participant = QtWidgets.QPushButton(Event)
        self.pushButton_del_event_participant.setObjectName("pushButton_del_event_participant")
        self.gridLayout.addWidget(self.pushButton_del_event_participant, 20, 0, 1, 1)
        self.line = QtWidgets.QFrame(Event)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 10, 0, 1, 7)
        self.tree_event_participants_list = QtWidgets.QTreeWidget(Event)
        self.tree_event_participants_list.setColumnCount(7)
        self.tree_event_participants_list.setObjectName("tree_event_participants_list")
        self.tree_event_participants_list.headerItem().setText(1, "2")
        self.tree_event_participants_list.headerItem().setText(2, "3")
        self.tree_event_participants_list.headerItem().setText(3, "4")
        self.tree_event_participants_list.headerItem().setText(4, "5")
        self.tree_event_participants_list.headerItem().setText(5, "6")
        self.tree_event_participants_list.headerItem().setText(6, "7")
        self.tree_event_participants_list.header().setDefaultSectionSize(120)
        self.tree_event_participants_list.header().setHighlightSections(True)
        self.tree_event_participants_list.header().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tree_event_participants_list, 12, 0, 7, 6)
        self.label_username_login_role = QtWidgets.QLabel(Event)
        self.label_username_login_role.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.label_username_login_role.setFont(font)
        self.label_username_login_role.setAutoFillBackground(False)
        self.label_username_login_role.setTextFormat(QtCore.Qt.AutoText)
        self.label_username_login_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_login_role.setObjectName("label_username_login_role")
        self.gridLayout.addWidget(self.label_username_login_role, 1, 4, 1, 3)
        self.lineEdit_event_country = QtWidgets.QLineEdit(Event)
        self.lineEdit_event_country.setObjectName("lineEdit_event_country")
        self.gridLayout.addWidget(self.lineEdit_event_country, 7, 2, 1, 1)
        self.pushButton_sms = QtWidgets.QPushButton(Event)
        self.pushButton_sms.setObjectName("pushButton_sms")
        self.gridLayout.addWidget(self.pushButton_sms, 13, 6, 1, 1)
        self.pushButton_close_access = QtWidgets.QPushButton(Event)
        self.pushButton_close_access.setObjectName("pushButton_close_access")
        self.gridLayout.addWidget(self.pushButton_close_access, 6, 4, 1, 1)
        self.pushButton_open_access = QtWidgets.QPushButton(Event)
        self.pushButton_open_access.setObjectName("pushButton_open_access")
        self.gridLayout.addWidget(self.pushButton_open_access, 5, 4, 1, 1)
        self.pushButton_load_xls = QtWidgets.QPushButton(Event)
        self.pushButton_load_xls.setObjectName("pushButton_load_xls")
        self.gridLayout.addWidget(self.pushButton_load_xls, 19, 1, 1, 1)

        self.retranslateUi(Event)
        self.pushButton_add_event_participant.clicked.connect(Event.show)
        self.pushButton_analisis_doc.clicked.connect(Event.show)
        self.pushButton_close_access.clicked.connect(Event.show)
        self.pushButton_del_event_participant.clicked.connect(self.tree_event_participants_list.update)
        self.pushButton_email.clicked.connect(Event.lower)
        self.pushButton_load_xls.clicked.connect(self.tree_event_participants_list.clear)
        self.pushButton_open_access.clicked.connect(Event.repaint)
        self.pushButton_print_list.clicked.connect(Event.hide)
        self.pushButton_sms.clicked.connect(Event.setFocus)
        self.pushButton_ok.clicked.connect(Event.show)
        self.pushButton_cancel.clicked.connect(Event.close)
        QtCore.QMetaObject.connectSlotsByName(Event)
        Event.setTabOrder(self.lineEdit_event_name, self.lineEdit_event_theme)
        Event.setTabOrder(self.lineEdit_event_theme, self.pushButton_select_organization)
        Event.setTabOrder(self.pushButton_select_organization, self.event_dateTime)
        Event.setTabOrder(self.event_dateTime, self.lineEdit_selected_organization)
        Event.setTabOrder(self.lineEdit_selected_organization, self.lineEdit_type_event)
        Event.setTabOrder(self.lineEdit_type_event, self.lineEdit_event_country)
        Event.setTabOrder(self.lineEdit_event_country, self.lineEdit_event_city)
        Event.setTabOrder(self.lineEdit_event_city, self.tree_event_participants_list)
        Event.setTabOrder(self.tree_event_participants_list, self.pushButton_add_event_participant)
        Event.setTabOrder(self.pushButton_add_event_participant, self.pushButton_del_event_participant)
        Event.setTabOrder(self.pushButton_del_event_participant, self.pushButton_load_xls)
        Event.setTabOrder(self.pushButton_load_xls, self.pushButton_open_access)
        Event.setTabOrder(self.pushButton_open_access, self.pushButton_close_access)
        Event.setTabOrder(self.pushButton_close_access, self.pushButton_analisis_doc)
        Event.setTabOrder(self.pushButton_analisis_doc, self.pushButton_sms)
        Event.setTabOrder(self.pushButton_sms, self.pushButton_email)
        Event.setTabOrder(self.pushButton_email, self.pushButton_print_list)
        Event.setTabOrder(self.pushButton_print_list, self.pushButton_ok)
        Event.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, Event):
        _translate = QtCore.QCoreApplication.translate
        Event.setWindowTitle(_translate("Event", "Event"))
        self.lineEdit_selected_organization.setPlaceholderText(_translate("Event", "Организация..."))
        self.pushButton_analisis_doc.setText(_translate("Event", "Анализ загруженных документов"))
        self.pushButton_cancel.setText(_translate("Event", "Отмена"))
        self.label_total_participants.setText(_translate("Event", "Кол-во участников ___"))
        self.label_Event.setText(_translate("Event", "Мероприятие"))
        self.pushButton_email.setText(_translate("Event", "e-mail"))
        self.lineEdit_event_city.setPlaceholderText(_translate("Event", "Город..."))
        self.pushButton_add_event_participant.setText(_translate("Event", "Добавить участника"))
        self.pushButton_select_organization.setText(_translate("Event", "Выбрать организацию"))
        self.pushButton_ok.setText(_translate("Event", "OK"))
        self.lineEdit_event_name.setPlaceholderText(_translate("Event", "Наименование мероприятия..."))
        self.lineEdit_type_event.setPlaceholderText(_translate("Event", "Тип мероприятия..."))
        self.pushButton_print_list.setText(_translate("Event", "Печать"))
        self.lineEdit_event_theme.setPlaceholderText(_translate("Event", "Тема мероприятия..."))
        self.label_list_participants.setText(_translate("Event", "Список участников"))
        self.pushButton_del_event_participant.setText(_translate("Event", "Удалить участника"))
        self.tree_event_participants_list.headerItem().setText(0, _translate("Event", "1"))
        self.label_username_login_role.setText(_translate("Event", "username_login_role"))
        self.lineEdit_event_country.setPlaceholderText(_translate("Event", "Страна..."))
        self.pushButton_sms.setText(_translate("Event", "SMS"))
        self.pushButton_close_access.setText(_translate("Event", "Закрыть доступ для организации"))
        self.pushButton_open_access.setText(_translate("Event", "Открыть доступ для организации"))
        self.pushButton_load_xls.setWhatsThis(_translate("Event", "Активна только если участников = 0"))
        self.pushButton_load_xls.setText(_translate("Event", "Загрузить файл с участниками (*.xls)"))
