# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Load_progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Load_progress(object):
    def setupUi(self, Load_progress):
        Load_progress.setObjectName("Load_progress")
        Load_progress.resize(517, 120)
        self.gridLayout = QtWidgets.QGridLayout(Load_progress)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_ok = QtWidgets.QPushButton(Load_progress)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout.addWidget(self.pushButton_ok, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Load_progress)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 3, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Load_progress)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 3)
        self.label_dialog = QtWidgets.QLabel(Load_progress)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_dialog.setFont(font)
        self.label_dialog.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dialog.setObjectName("label_dialog")
        self.gridLayout.addWidget(self.label_dialog, 0, 0, 1, 3)
        self.label_dialog_1 = QtWidgets.QLabel(Load_progress)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_dialog_1.setFont(font)
        self.label_dialog_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dialog_1.setObjectName("label_dialog_1")
        self.gridLayout.addWidget(self.label_dialog_1, 1, 0, 1, 3)

        self.retranslateUi(Load_progress)
        self.pushButton_cancel.clicked.connect(Load_progress.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Load_progress)

    def retranslateUi(self, Load_progress):
        _translate = QtCore.QCoreApplication.translate
        Load_progress.setWindowTitle(_translate("Load_progress", "Загрузка файла xls"))
        self.pushButton_ok.setText(_translate("Load_progress", "OK"))
        self.pushButton_cancel.setText(_translate("Load_progress", "Отмена"))
        self.label_dialog.setText(_translate("Load_progress", "Файл готов к загрузке. "))
        self.label_dialog_1.setText(_translate("Load_progress", "Загрузить?"))
