# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Send_email.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Send_email(object):
    def setupUi(self, Send_email):
        Send_email.setObjectName("Send_email")
        Send_email.resize(714, 431)
        self.gridLayout = QtWidgets.QGridLayout(Send_email)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_theme_email = QtWidgets.QLineEdit(Send_email)
        self.lineEdit_theme_email.setObjectName("lineEdit_theme_email")
        self.gridLayout.addWidget(self.lineEdit_theme_email, 4, 0, 1, 4)
        self.label_send_go_on = QtWidgets.QLabel(Send_email)
        self.label_send_go_on.setEnabled(True)
        self.label_send_go_on.setAutoFillBackground(True)
        self.label_send_go_on.setText("")
        self.label_send_go_on.setAlignment(QtCore.Qt.AlignCenter)
        self.label_send_go_on.setObjectName("label_send_go_on")
        self.gridLayout.addWidget(self.label_send_go_on, 8, 1, 1, 2)
        self.pushButton_cancel = QtWidgets.QPushButton(Send_email)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 9, 2, 1, 1)
        self.pushButton_send = QtWidgets.QPushButton(Send_email)
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout.addWidget(self.pushButton_send, 9, 3, 1, 1)
        self.label_email_theme = QtWidgets.QLabel(Send_email)
        self.label_email_theme.setObjectName("label_email_theme")
        self.gridLayout.addWidget(self.label_email_theme, 3, 0, 1, 1)
        self.label_send_email = QtWidgets.QLabel(Send_email)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_send_email.setFont(font)
        self.label_send_email.setAlignment(QtCore.Qt.AlignCenter)
        self.label_send_email.setObjectName("label_send_email")
        self.gridLayout.addWidget(self.label_send_email, 1, 0, 1, 4)
        self.label_email_body = QtWidgets.QLabel(Send_email)
        self.label_email_body.setObjectName("label_email_body")
        self.gridLayout.addWidget(self.label_email_body, 5, 0, 1, 4)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Send_email)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 6, 0, 1, 4)
        self.label_sure_exist_email = QtWidgets.QLabel(Send_email)
        self.label_sure_exist_email.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sure_exist_email.setObjectName("label_sure_exist_email")
        self.gridLayout.addWidget(self.label_sure_exist_email, 0, 0, 1, 4)
        self.progressBar = QtWidgets.QProgressBar(Send_email)
        self.progressBar.setEnabled(False)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 7, 1, 1, 2)

        self.retranslateUi(Send_email)
        self.pushButton_cancel.clicked.connect(Send_email.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Send_email)

    def retranslateUi(self, Send_email):
        _translate = QtCore.QCoreApplication.translate
        Send_email.setWindowTitle(_translate("Send_email", "Dialog"))
        self.pushButton_cancel.setText(_translate("Send_email", "Отменить"))
        self.pushButton_send.setText(_translate("Send_email", "Отправить"))
        self.label_email_theme.setText(_translate("Send_email", "Тема письма"))
        self.label_send_email.setText(_translate("Send_email", "Отправка e-mail всем  участникам мероприятия"))
        self.label_email_body.setText(_translate("Send_email", "Текст сообщения"))
        self.plainTextEdit.setPlainText(_translate("Send_email", "Уважаемый {full_name}!\n"
"Для участия в мероприятии {event_name} вам необходимо загрузить документы в личный кабинет участника.\n"
"Личный кабинет доступен по адресу:\n"
"http://lk.mgido.com\n"
"Для входа используйте логин:\n"
"{phone_number}\n"
"\n"
"Пароль:\n"
"{password}"))
        self.label_sure_exist_email.setText(_translate("Send_email", "Убедитесь, что все участники в списке имеют  email"))
