# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Upload_docs.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Upload_docs(object):
    def setupUi(self, Upload_docs):
        Upload_docs.setObjectName("Upload_docs")
        Upload_docs.resize(315, 510)
        self.gridLayout = QtWidgets.QGridLayout(Upload_docs)
        self.gridLayout.setObjectName("gridLayout")
        self.label_sertificate_upload = QtWidgets.QLabel(Upload_docs)
        self.label_sertificate_upload.setObjectName("label_sertificate_upload")
        self.gridLayout.addWidget(self.label_sertificate_upload, 10, 1, 1, 1)
        self.label_passport_upload = QtWidgets.QLabel(Upload_docs)
        self.label_passport_upload.setObjectName("label_passport_upload")
        self.gridLayout.addWidget(self.label_passport_upload, 5, 1, 1, 1)
        self.label_event = QtWidgets.QLabel(Upload_docs)
        self.label_event.setAlignment(QtCore.Qt.AlignCenter)
        self.label_event.setObjectName("label_event")
        self.gridLayout.addWidget(self.label_event, 2, 0, 1, 2)
        self.pushButton_upload_sertificate = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_sertificate.setObjectName("pushButton_upload_sertificate")
        self.gridLayout.addWidget(self.pushButton_upload_sertificate, 10, 0, 1, 1)
        self.pushButton_upload_agreement = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_agreement.setObjectName("pushButton_upload_agreement")
        self.gridLayout.addWidget(self.pushButton_upload_agreement, 11, 0, 1, 1)
        self.pushButton_upload_registration = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_registration.setObjectName("pushButton_upload_registration")
        self.gridLayout.addWidget(self.pushButton_upload_registration, 6, 0, 1, 1)
        self.label_contract_upload = QtWidgets.QLabel(Upload_docs)
        self.label_contract_upload.setObjectName("label_contract_upload")
        self.gridLayout.addWidget(self.label_contract_upload, 13, 1, 1, 1)
        self.pushButton_upload_survey = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_survey.setObjectName("pushButton_upload_survey")
        self.gridLayout.addWidget(self.pushButton_upload_survey, 12, 0, 1, 1)
        self.pushButton_upload_report = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_report.setObjectName("pushButton_upload_report")
        self.gridLayout.addWidget(self.pushButton_upload_report, 15, 0, 1, 1)
        self.pushButton_upload_contract = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_contract.setObjectName("pushButton_upload_contract")
        self.gridLayout.addWidget(self.pushButton_upload_contract, 13, 0, 1, 1)
        self.pushButton_upload_act = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_act.setObjectName("pushButton_upload_act")
        self.gridLayout.addWidget(self.pushButton_upload_act, 14, 0, 1, 1)
        self.label_survey_upload = QtWidgets.QLabel(Upload_docs)
        self.label_survey_upload.setObjectName("label_survey_upload")
        self.gridLayout.addWidget(self.label_survey_upload, 12, 1, 1, 1)
        self.label_agreement_upload = QtWidgets.QLabel(Upload_docs)
        self.label_agreement_upload.setObjectName("label_agreement_upload")
        self.gridLayout.addWidget(self.label_agreement_upload, 11, 1, 1, 1)
        self.label_registration_upload = QtWidgets.QLabel(Upload_docs)
        self.label_registration_upload.setObjectName("label_registration_upload")
        self.gridLayout.addWidget(self.label_registration_upload, 6, 1, 1, 1)
        self.label_upload = QtWidgets.QLabel(Upload_docs)
        self.label_upload.setAlignment(QtCore.Qt.AlignCenter)
        self.label_upload.setObjectName("label_upload")
        self.gridLayout.addWidget(self.label_upload, 4, 0, 1, 1)
        self.label_diploma_upload = QtWidgets.QLabel(Upload_docs)
        self.label_diploma_upload.setObjectName("label_diploma_upload")
        self.gridLayout.addWidget(self.label_diploma_upload, 9, 1, 1, 1)
        self.pushButton_upload_diploma = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_diploma.setObjectName("pushButton_upload_diploma")
        self.gridLayout.addWidget(self.pushButton_upload_diploma, 9, 0, 1, 1)
        self.label_snils_upload = QtWidgets.QLabel(Upload_docs)
        self.label_snils_upload.setObjectName("label_snils_upload")
        self.gridLayout.addWidget(self.label_snils_upload, 8, 1, 1, 1)
        self.pushButton_upload_snils = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_snils.setObjectName("pushButton_upload_snils")
        self.gridLayout.addWidget(self.pushButton_upload_snils, 8, 0, 1, 1)
        self.label_username_login_role = QtWidgets.QLabel(Upload_docs)
        self.label_username_login_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_login_role.setObjectName("label_username_login_role")
        self.gridLayout.addWidget(self.label_username_login_role, 0, 0, 1, 2)
        self.pushButton_ok = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout.addWidget(self.pushButton_ok, 17, 1, 1, 1)
        self.label_inn_upload = QtWidgets.QLabel(Upload_docs)
        self.label_inn_upload.setObjectName("label_inn_upload")
        self.gridLayout.addWidget(self.label_inn_upload, 7, 1, 1, 1)
        self.pushButton_upload_inn = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_inn.setObjectName("pushButton_upload_inn")
        self.gridLayout.addWidget(self.pushButton_upload_inn, 7, 0, 1, 1)
        self.label_participant_full_name = QtWidgets.QLabel(Upload_docs)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_participant_full_name.setFont(font)
        self.label_participant_full_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_participant_full_name.setObjectName("label_participant_full_name")
        self.gridLayout.addWidget(self.label_participant_full_name, 1, 0, 1, 2)
        self.label_report_upload = QtWidgets.QLabel(Upload_docs)
        self.label_report_upload.setObjectName("label_report_upload")
        self.gridLayout.addWidget(self.label_report_upload, 15, 1, 1, 1)
        self.pushButton_upload_passport = QtWidgets.QPushButton(Upload_docs)
        self.pushButton_upload_passport.setObjectName("pushButton_upload_passport")
        self.gridLayout.addWidget(self.pushButton_upload_passport, 5, 0, 1, 1)
        self.label_act_upload = QtWidgets.QLabel(Upload_docs)
        self.label_act_upload.setObjectName("label_act_upload")
        self.gridLayout.addWidget(self.label_act_upload, 14, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 16, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)

        self.retranslateUi(Upload_docs)
        self.pushButton_ok.clicked.connect(Upload_docs.close)
        self.pushButton_upload_passport.clicked.connect(Upload_docs.show)
        self.pushButton_upload_registration.clicked.connect(Upload_docs.show)
        self.pushButton_upload_inn.clicked.connect(Upload_docs.show)
        self.pushButton_upload_snils.clicked.connect(Upload_docs.show)
        self.pushButton_upload_diploma.clicked.connect(Upload_docs.show)
        self.pushButton_upload_sertificate.clicked.connect(Upload_docs.show)
        self.pushButton_upload_survey.clicked.connect(Upload_docs.show)
        self.pushButton_upload_agreement.clicked.connect(Upload_docs.show)
        self.pushButton_upload_contract.clicked.connect(Upload_docs.show)
        self.pushButton_upload_act.clicked.connect(Upload_docs.show)
        self.pushButton_upload_report.clicked.connect(Upload_docs.show)
        QtCore.QMetaObject.connectSlotsByName(Upload_docs)
        Upload_docs.setTabOrder(self.pushButton_upload_passport, self.pushButton_upload_registration)
        Upload_docs.setTabOrder(self.pushButton_upload_registration, self.pushButton_upload_inn)
        Upload_docs.setTabOrder(self.pushButton_upload_inn, self.pushButton_upload_snils)
        Upload_docs.setTabOrder(self.pushButton_upload_snils, self.pushButton_upload_diploma)
        Upload_docs.setTabOrder(self.pushButton_upload_diploma, self.pushButton_upload_sertificate)
        Upload_docs.setTabOrder(self.pushButton_upload_sertificate, self.pushButton_upload_agreement)
        Upload_docs.setTabOrder(self.pushButton_upload_agreement, self.pushButton_upload_survey)
        Upload_docs.setTabOrder(self.pushButton_upload_survey, self.pushButton_upload_contract)
        Upload_docs.setTabOrder(self.pushButton_upload_contract, self.pushButton_upload_act)
        Upload_docs.setTabOrder(self.pushButton_upload_act, self.pushButton_upload_report)
        Upload_docs.setTabOrder(self.pushButton_upload_report, self.pushButton_ok)

    def retranslateUi(self, Upload_docs):
        _translate = QtCore.QCoreApplication.translate
        Upload_docs.setWindowTitle(_translate("Upload_docs", "Event"))
        self.label_sertificate_upload.setText(_translate("Upload_docs", "Файл не загружен"))
        self.label_passport_upload.setText(_translate("Upload_docs", "Файл не загружен"))
        self.label_event.setText(_translate("Upload_docs", "Event"))
        self.pushButton_upload_sertificate.setText(_translate("Upload_docs", "Сертификат"))
        self.pushButton_upload_agreement.setText(_translate("Upload_docs", "Согласие"))
        self.pushButton_upload_registration.setText(_translate("Upload_docs", "Регистрация"))
        self.label_contract_upload.setText(_translate("Upload_docs", "Файл не загружен"))
        self.pushButton_upload_survey.setText(_translate("Upload_docs", "Анкета"))
        self.pushButton_upload_report.setText(_translate("Upload_docs", "Отчет"))
        self.pushButton_upload_contract.setText(_translate("Upload_docs", "Договор"))
        self.pushButton_upload_act.setText(_translate("Upload_docs", "Акт"))
        self.label_survey_upload.setText(_translate("Upload_docs", "Файл не загружен"))
        self.label_agreement_upload.setText(_translate("Upload_docs", "Файл не загружен"))
        self.label_registration_upload.setText(_translate("Upload_docs", "Файл не загружен"))
        self.label_upload.setText(_translate("Upload_docs", "Загрузить"))
        self.label_diploma_upload.setText(_translate("Upload_docs", "Файл не загружен"))
        self.pushButton_upload_diploma.setText(_translate("Upload_docs", "Диплом"))
        self.label_snils_upload.setText(_translate("Upload_docs", "Файл не загружен"))
        self.pushButton_upload_snils.setText(_translate("Upload_docs", "СНИЛС"))
        self.label_username_login_role.setText(_translate("Upload_docs", "username_login_role"))
        self.pushButton_ok.setText(_translate("Upload_docs", "ОК"))
        self.label_inn_upload.setText(_translate("Upload_docs", "Файл не загружен"))
        self.pushButton_upload_inn.setText(_translate("Upload_docs", "ИНН"))
        self.label_participant_full_name.setText(_translate("Upload_docs", "Participant_full_name"))
        self.label_report_upload.setText(_translate("Upload_docs", "Файл не загружен"))
        self.pushButton_upload_passport.setText(_translate("Upload_docs", "Паспорт"))
        self.label_act_upload.setText(_translate("Upload_docs", "Файл не загружен"))
